"""remove_requested_date_and_link_appointment

Revision ID: 448b90860c1e
Revises: 5821251d4c37
Create Date: 2026-07-06 09:42:29.844442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '448b90860c1e'
down_revision: Union[str, Sequence[str], None] = '5821251d4c37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_requests', sa.Column('appointment_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'booking_requests', 'appointments', ['appointment_id'], ['appointment_id'])
    op.drop_column('booking_requests', 'requested_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_requests', sa.Column('requested_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'booking_requests', type_='foreignkey')
    op.drop_column('booking_requests', 'appointment_id')
    # ### end Alembic commands ###
