"""make_doctor_id_required_and_remove_requested_end_time

Revision ID: e656effc189d
Revises: 448b90860c1e
Create Date: 2026-07-07 09:22:10.491953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e656effc189d'
down_revision: Union[str, Sequence[str], None] = '448b90860c1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booking_requests', 'doctor_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('booking_requests', 'requested_end_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_requests', sa.Column('requested_end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('booking_requests', 'doctor_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
